input.onButtonPressed(Button.A, function () {
    bitbot.setLedColor(0xFF0000)
    basic.showIcon(IconNames.Sad)
    bitbot.rotatems(BBRobotDirection.Left, 60, 350)
    bitbot.goms(BBDirection.Reverse, 60, 2000)
    bitbot.stop(BBStopMode.Brake)
    basic.pause(5000)
    basic.showIcon(IconNames.Happy)
    bitbot.ledRainbow()
    bitbot.goms(BBDirection.Forward, 60, 2000)
    bitbot.rotatems(BBRobotDirection.Right, 60, 350)
})
input.onButtonPressed(Button.AB, function () {
    bitbot.goms(BBDirection.Forward, 60, 4000)
    bitbot.stop(BBStopMode.Brake)
    basic.pause(5000)
    basic.showIcon(IconNames.Sad)
    bitbot.setLedColor(0xFF0000)
    bitbot.rotatems(BBRobotDirection.Right, 60, 500)
    bitbot.goms(BBDirection.Reverse, 60, 4000)
    bitbot.stop(BBStopMode.Brake)
    basic.pause(5000)
    basic.showIcon(IconNames.Happy)
    bitbot.ledRainbow()
    bitbot.goms(BBDirection.Forward, 60, 4000)
})
input.onButtonPressed(Button.B, function () {
    bitbot.goms(BBDirection.Forward, 60, 4000)
    bitbot.stop(BBStopMode.Brake)
    basic.pause(5000)
    basic.showIcon(IconNames.Sad)
    bitbot.setLedColor(0xFF0000)
    bitbot.goms(BBDirection.Reverse, 60, 4000)
    bitbot.stop(BBStopMode.Brake)
    basic.pause(5000)
    basic.showIcon(IconNames.Happy)
    bitbot.ledRainbow()
    bitbot.goms(BBDirection.Forward, 60, 4000)
})
basic.showIcon(IconNames.Happy)
bitbot.setLedColor(0x00FF00)
